<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-RK577T0" failures="1" tests="5" name="Default test(failed)" time="0.098" errors="0" timestamp="2022-08-09T15:33:06 IST">
  <testcase classname="practice.DemoRetry" name="modifyContact" time="0.01">
    <skipped/>
  </testcase> <!-- modifyContact -->
  <testcase classname="practice.DemoRetry" name="modifyContact" time="0.002">
    <skipped/>
  </testcase> <!-- modifyContact -->
  <testcase classname="practice.DemoRetry" name="modifyContact" time="0.001">
    <skipped/>
  </testcase> <!-- modifyContact -->
  <testcase classname="practice.DemoRetry" name="modifyContact" time="0.001">
    <skipped/>
  </testcase> <!-- modifyContact -->
  <testcase classname="practice.DemoRetry" name="modifyContact" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at practice.DemoRetry.modifyContact(DemoRetry.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- modifyContact -->
</testsuite> <!-- Default test(failed) -->
